Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"
  config.vm.provider :libvirt do |lv|
    lv.cpus = 1; lv.memory = 1024; lv.graphics_type = "none"
  end
  config.vm.network "private_network", ip: "192.168.56.10"  # 測一塊私網
  config.ssh.insert_key = false
end
